### ISSUE TITLE
Need a badge

### ISSUE THREAD

**Issue by feross** [mafintosh/abstract-chunk-store#1]

**Comment by feross** [comment]
@maxogden @ngoldman Do either of you have the original SVG source for the standard badge? We could reuse it here!

**Comment by ungoldman** [comment]
Sorry @feross I wasn't able to find the source SVG -- the one I was able to find doesn't have the original layers and font information. I remember it was Source Sans Pro. http://cl.ly/0t3R071L1h3i

**Comment by ungoldman** [comment]
What kind of badge is needed here @feross?

(following up on old issues I've been mentioned in)

**Comment by feross** [comment]
Something like the standard badge. If you can find the original file with the font still in it, it would be an easy modification.

**Comment by feross** [comment]
![abstract-chunk-store](https://cloud.githubusercontent.com/assets/121766/14968025/e3f1318c-10ba-11e6-806f-a0af70f19c56.png)
