### ISSUE TITLE
Why a numeric chunk index?

### ISSUE THREAD

**Issue by jhead** [mafintosh/abstract-chunk-store#2]
What's the thinking behind requiring a numeric index for each chunk, rather than something arbitrary as in a map (such as a hash)?

**Comment by feross** [comment]
We need the chunks to be ordered. We could have allowed arbitrary keys but that would have made implementing [`fs-chunk-store`](https://npmjs.com/package/fs-chunk-store) way more complicated. Numeric indexes map nicely to file-like stores.

**Comment by feross** [comment]
@mafintosh might have other use cases in mind, too.

**Comment by mafintosh** [comment]
Like @feross said this is meant for low level storage engines where numeric ids are really useful. You could implement a thing that stores the hashes somewhere else and maps to a chunk-store numeric id

**Comment by jhead** [comment]
@mafintosh great idea :+1:
